import subprocess
import sys
import os

def test_ghost_service_detection():
    # We scan the entire SAMPLES directory to give Synapse context
    # so it can see the mismatch between services and deployments.
    sample_dir = "tests/samples/"
    
    result = subprocess.run(
        [sys.executable, "-m", "kubecuro.main", "scan", sample_dir],
        capture_output=True,
        text=True
    )

    # Useful for debugging in GitHub Actions logs
    print(f"STDOUT: {result.stdout}")
    
    # Check for the actual error message generated by Synapse
    # This proves the logic engine successfully identified the orphan service.
    assert "GHOST SERVICE" in result.stdout
    assert "matches 0 workload pods" in result.stdout

def test_healthy_connection():
    # Scan only the valid file to ensure no false positives
    target = "tests/samples/valid_connection.yaml"
    
    result = subprocess.run(
        [sys.executable, "-m", "kubecuro.main", "scan", target],
        capture_output=True,
        text=True
    )
    
    # We should NOT see the Ghost Service warning here
    assert "GHOST SERVICE" not in result.stdout
